apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-signin
  labels:
    app: journal-signin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-signin
  template:
    metadata:
      labels:
        app: journal-signin
    spec:
      containers:
        - name: journal-signin-app # Container name
          image: journal-signin-app:latest # Docker image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # Expose port 8081 from the container
          env:
           - name: SPRING_R2DBC_URL
             value: r2dbc:mysql://journallab2-db:3306/journaldb
           - name: SPRING_R2DBC_USERNAME
             value: root
           - name: SPRING_R2DBC_PASSWORD
             value: "1234"
